const auditFields = {
  created_at: "2025-01-15",
  created_by: 1,
  deleted_at: null,
  deleted_by: null,
  delete_explanation: null,
};

export const databases = [
  {
    id: 1,
    name: "Scopus",
    description: "Base de datos de resúmenes y citas de literatura científica revisada por pares, con herramientas para analizar la producción académica.",
    institution: "Elsevier",
    country: "Países Bajos",
    url: "https://www.scopus.com/",
    geographic_coverage: "Internacional",
    language: "Multilingüe",
    coverage_period: "Desde 1960",
    material_type: "Artículos, libros y actas de congreso",
    license: "Institucional",
    identifiers: [{ identifier_type: "ISSN", identifier_value: "N/A" }],
    links: [{ link_type: "Sitio oficial", url: "https://www.scopus.com/" }],
    subject_areas: ["Ciencias de la salud", "Ingeniería", "Ciencias sociales"],
    academic_programs: ["Investigación", "Posgrado"],
    is_active: true,
    ...auditFields,
  },
  {
    id: 2,
    name: "EBSCOhost",
    description: "Plataforma de investigación que reúne revistas, libros y fuentes especializadas de múltiples disciplinas.",
    institution: "EBSCO Information Services",
    country: "Estados Unidos",
    url: "https://search.ebscohost.com/",
    geographic_coverage: "Internacional",
    language: "Inglés y español",
    coverage_period: "Desde 1880",
    material_type: "Revistas, libros y reportes",
    license: "Institucional",
    identifiers: [{ identifier_type: "Plataforma", identifier_value: "EBSCOhost" }],
    links: [{ link_type: "Sitio oficial", url: "https://search.ebscohost.com/" }],
    subject_areas: ["Humanidades", "Ciencias sociales", "Educación"],
    academic_programs: ["Educación", "Ciencias sociales"],
    is_active: true,
    ...auditFields,
  },
  {
    id: 3,
    name: "IEEE Xplore",
    description: "Colección digital de literatura técnica y científica en ingeniería eléctrica, computación y tecnologías relacionadas.",
    institution: "Institute of Electrical and Electronics Engineers",
    country: "Estados Unidos",
    url: "https://ieeexplore.ieee.org/",
    geographic_coverage: "Internacional",
    language: "Inglés",
    coverage_period: "Desde 1893",
    material_type: "Artículos, estándares y actas",
    license: "Institucional",
    identifiers: [{ identifier_type: "Plataforma", identifier_value: "IEEE Xplore" }],
    links: [{ link_type: "Sitio oficial", url: "https://ieeexplore.ieee.org/" }],
    subject_areas: ["Ingeniería", "Tecnología"],
    academic_programs: ["Ingeniería", "Informática"],
    is_active: true,
    ...auditFields,
  },
];

export const journals = [
  {
    id: 1,
    name: "Revista de Salud Pública",
    description: "Publicación científica de acceso abierto dedicada a la investigación y el debate en salud pública y disciplinas afines.",
    institution: "Universidad Nacional de Colombia",
    country: "Colombia",
    url: "https://revistas.unal.edu.co/",
    geographic_coverage: "América Latina",
    language: "Español, inglés y portugués",
    coverage_period: "2010–actualidad",
    material_type: "Revista científica",
    license: "Acceso abierto · CC BY-NC",
    identifiers: [
      { identifier_type: "ISSN impreso", identifier_value: "0124-0064" },
      { identifier_type: "ISSN electrónico", identifier_value: "2539-3596" },
    ],
    links: [{ link_type: "Sitio oficial", url: "https://revistas.unal.edu.co/" }],
    subject_areas: ["Ciencias de la salud", "Salud pública"],
    database_ids: [1, 2],
    is_active: true,
    ...auditFields,
  },
  {
    id: 2,
    name: "Ingeniería e Investigación",
    description: "Revista de investigación que difunde resultados originales en ingeniería, ciencia aplicada e innovación tecnológica.",
    institution: "Universidad Nacional de Colombia",
    country: "Colombia",
    url: "https://revistas.unal.edu.co/",
    geographic_coverage: "Internacional",
    language: "Español e inglés",
    coverage_period: "1981–actualidad",
    material_type: "Revista científica",
    license: "Acceso abierto · CC BY",
    identifiers: [
      { identifier_type: "ISSN impreso", identifier_value: "0120-5609" },
      { identifier_type: "ISSN electrónico", identifier_value: "2248-8723" },
    ],
    links: [{ link_type: "Sitio oficial", url: "https://revistas.unal.edu.co/" }],
    subject_areas: ["Ingeniería", "Tecnología"],
    database_ids: [1, 3],
    is_active: true,
    ...auditFields,
  },
];